---
# vars file for analysis
analysis_convert2rhel_enable_repos_args: "{{ ('--enablerepo ' + analysis_convert2rhel_repos_enabled | default([], true) | join(' --enablerepo ')) if analysis_convert2rhel_repos_enabled | length > 0 else '' }}"
analysis_convert2rhel_disable_repos_args: "{{ ('--disablerepo ' + analysis_convert2rhel_repos_disabled | default([], true) | join(' --disablerepo ')) if analysis_convert2rhel_repos_disabled | length > 0 else '' }}"

# used only in handlers/main.yml
analysis_result_filename_prefix: /var/log/convert2rhel/convert2rhel-pre-conversion
analysis_result_filename_txt: "{{ analysis_result_filename_prefix }}.txt"
...
